<?php

return [
    'tat-ca-san-pham' => [
        'title' => 'Tất cả sản phẩm',
        'path' => '/onlinestore/public/product.php',
        'categoryId' => -1,
        'keywords' => [],
        'defaultSort' => 'newest',
        'showInSidebar' => true,
    ],
    'san-pham-moi' => [
        'title' => 'Sản phẩm mới',
        'path' => '/onlinestore/public/new_arrivals.php',
        'categoryId' => -1,
        'keywords' => [],
        'isNew' => true,
        'defaultSort' => 'newest',
        'showInSidebar' => true,
        'banner' => [
            'mode' => 'image-only',
            'image' => '/onlinestore/public/images/banner_spmoi.png',
        ],
    ],
    'dat-truoc' => [
        'title' => 'Đặt trước',
        'path' => '/onlinestore/public/dat_truoc.php',
        'categoryId' => -1,
        'keywords' => ['đặt trước'],
        'defaultSort' => 'newest',
        'showInSidebar' => true,
    ],
    'ao' => [
        'title' => 'Áo',
        'path' => '/onlinestore/public/ao.php',
        'categoryId' => 1,
        'keywords' => [],
        'defaultSort' => 'newest',
        'showInSidebar' => true,
    ],
    'dam' => [
        'title' => 'Đầm',
        'path' => '/onlinestore/public/dam.php',
        'categoryId' => 4,
        'keywords' => [],
        'defaultSort' => 'newest',
        'showInSidebar' => true,
    ],
    'yem' => [
        'title' => 'Yếm',
        'path' => '/onlinestore/public/yem.php',
        'categoryId' => 5,
        'keywords' => [],
        'defaultSort' => 'newest',
        'showInSidebar' => true,
    ],
    'quan-shorts' => [
        'title' => 'Quần Shorts',
        'path' => '/onlinestore/public/quan_shorts.php',
        'categoryId' => 6,
        'keywords' => [],
        'defaultSort' => 'newest',
        'showInSidebar' => true,
    ],
    'quan-ong-rong' => [
        'title' => 'Quần ống rộng',
        'path' => '/onlinestore/public/quan_ong_rong.php',
        'categoryId' => 7,
        'keywords' => [],
        'defaultSort' => 'newest',
        'showInSidebar' => true,
    ],
    'chan-vay' => [
        'title' => 'Chân váy',
        'path' => '/onlinestore/public/chan_vay.php',
        'categoryId' => 8,
        'keywords' => [],
        'defaultSort' => 'newest',
        'showInSidebar' => true,
    ],
    'phu-kien' => [
        'title' => 'Phụ kiện',
        'path' => '/onlinestore/public/phu_kien.php',
        'categoryId' => 3,
        'keywords' => [],
        'defaultSort' => 'newest',
        'showInSidebar' => true,
    ],
    'clair-de-spring' => [
        'title' => 'CLAIR DE SPRING',
        'path' => '/onlinestore/public/clair_de_spring.php',
        'categoryId' => -1,
        'keywords' => [],
        'collectionCode' => 'clair-de-spring',
        'defaultSort' => 'name_asc',
        'showInSidebar' => false,
        'banner' => [
            'mode' => 'image-only',
            'image' => '/onlinestore/public/images/ban1.png',
        ],
    ],
    'xuan-nhien' => [
        'title' => 'XUÂN NHIÊN',
        'path' => '/onlinestore/public/xuan_nhien.php',
        'categoryId' => -1,
        'keywords' => [],
        'collectionCode' => 'xuan-nhien',
        'defaultSort' => 'name_asc',
        'showInSidebar' => false,
        'banner' => [
            'mode' => 'image-only',
            'image' => '/onlinestore/public/images/ban2.png',
        ],
    ],
    'night-out' => [
        'title' => 'NIGHT OUT COLLECTION',
        'path' => '/onlinestore/public/night_out.php',
        'categoryId' => -1,
        'keywords' => [],
        'collectionCode' => 'night-out',
        'defaultSort' => 'name_asc',
        'showInSidebar' => false,
        'banner' => [
            'mode' => 'image-only',
            'image' => '/onlinestore/public/images/ban3.png',
        ],
    ],
    'city-hours' => [
        'title' => 'CITY HOURS',
        'path' => '/onlinestore/public/city_hours.php',
        'categoryId' => -1,
        'keywords' => [],
        'collectionCode' => 'city-hours',
        'defaultSort' => 'name_asc',
        'showInSidebar' => false,
        'banner' => [
            'mode' => 'image-only',
            'image' => '/onlinestore/public/images/ban4.png',
        ],
    ],
    'classmate-notes' => [
        'title' => 'CLASSMATE NOTES',
        'path' => '/onlinestore/public/classmate_notes.php',
        'categoryId' => -1,
        'keywords' => [],
        'collectionCode' => 'classmate-notes',
        'defaultSort' => 'name_asc',
        'showInSidebar' => false,
        'banner' => [
            'mode' => 'image-only',
            'image' => '/onlinestore/public/images/ban5.png',
        ],
    ],
    'after-class' => [
        'title' => 'AFTER CLASS',
        'path' => '/onlinestore/public/after_class.php',
        'categoryId' => -1,
        'keywords' => [],
        'collectionCode' => 'after-class',
        'defaultSort' => 'name_asc',
        'showInSidebar' => false,
    ],
];
