<?php

return [
    'tat-ca-san-pham' => [
        'title' => 'Tất cả sản phẩm',
        'path' => '/onlinestore/public/product.php',
        'categoryId' => -1,
        'keywords' => [],
        'defaultSort' => 'newest',
        'showInSidebar' => true,
    ],
    'san-pham-moi' => [
        'title' => 'Sản phẩm mới',
        'path' => '/onlinestore/public/new_arrivals.php',
        'categoryId' => -1,
        'keywords' => [],
        'isNew' => true,
        'defaultSort' => 'newest',
        'showInSidebar' => true,
        'banner' => [
            'mode' => 'image-only',
            'image' => '/onlinestore/public/images/banner_spmoi.png',
        ],
    ],
    'dat-truoc' => [
        'title' => 'Đặt trước',
        'path' => '/onlinestore/public/dat_truoc.php',
        'categoryId' => -1,
        'keywords' => ['đặt trước'],
        'defaultSort' => 'newest',
        'showInSidebar' => true,
    ],
    'ao' => [
        'title' => 'Áo',
        'path' => '/onlinestore/public/ao.php',
        'categoryId' => 1,
        'keywords' => [],
        'defaultSort' => 'newest',
        'showInSidebar' => true,
    ],
    'dam' => [
        'title' => 'Đầm',
        'path' => '/onlinestore/public/dam.php',
        'categoryId' => 4,
        'keywords' => [],
        'defaultSort' => 'newest',
        'showInSidebar' => true,
    ],
    'yem' => [
        'title' => 'Yếm',
        'path' => '/onlinestore/public/yem.php',
        'categoryId' => 5,
        'keywords' => [],
        'defaultSort' => 'newest',
        'showInSidebar' => true,
    ],
    'quan-shorts' => [
        'title' => 'Quần Shorts',
        'path' => '/onlinestore/public/quan_shorts.php',
        'categoryId' => 6,
        'keywords' => [],
        'defaultSort' => 'newest',
        'showInSidebar' => true,
    ],
    'quan-ong-rong' => [
        'title' => 'Quần ống rộng',
        'path' => '/onlinestore/public/quan_ong_rong.php',
        'categoryId' => 7,
        'keywords' => [],
        'defaultSort' => 'newest',
        'showInSidebar' => true,
    ],
    'chan-vay' => [
        'title' => 'Chân váy',
        'path' => '/onlinestore/public/chan_vay.php',
        'categoryId' => 8,
        'keywords' => [],
        'defaultSort' => 'newest',
        'showInSidebar' => true,
    ],
    'phu-kien' => [
        'title' => 'Phụ kiện',
        'path' => '/onlinestore/public/phu_kien.php',
        'categoryId' => 3,
        'keywords' => [],
        'defaultSort' => 'newest',
        'showInSidebar' => true,
    ],
];
